Don't mark resize_buf as inline, this causes problems on MacOS
When compiling without -O2 flag, loading generated library was failing with
error: symbol not found _resize_buf